FROM ubuntu:trusty
MAINTAINER Xiaohui <xiaohui@tanmer.com>

USER root
WORKDIR /root

ENV DEBIAN_FRONTEND noninteractive
RUN sed -i 's!^mesg n$!tty -s \&\& mesg n!' /root/.profile
RUN sed -i 's!http://archive.ubuntu.com!http://mirrors.aliyun.com!' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install wget curl git build-essential -y
